---

name: Perl CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.32', '5.34', '5.36', '5.38']

    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Install dependencies
        run: |
          cpanm --notest --installdeps .

      - name: Run tests
        run: |
          perl Makefile.PL
          make test
